# Generated by Django 5.0.14 on 2026-01-30 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AtributoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=60)),
                ('activo', models.BooleanField(default=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='catalogo.atributo')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=64)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogo.producto')),
            ],
        ),
        migrations.CreateModel(
            name='StockSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.variante')),
            ],
        ),
        migrations.CreateModel(
            name='VarianteAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.atributo')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.atributovalor')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='catalogo.variante')),
            ],
        ),
        migrations.AddIndex(
            model_name='atributovalor',
            index=models.Index(fields=['atributo', 'valor'], name='catalogo_at_atribut_20d9b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='atributovalor',
            unique_together={('atributo', 'valor')},
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='catalogo_pr_nombre_6cb059_idx'),
        ),
        migrations.AddIndex(
            model_name='variante',
            index=models.Index(fields=['producto', 'activo'], name='catalogo_va_product_1fdfd2_idx'),
        ),
        migrations.AddIndex(
            model_name='variante',
            index=models.Index(fields=['sku'], name='catalogo_va_sku_ed474e_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksucursal',
            index=models.Index(fields=['sucursal', 'variante'], name='catalogo_st_sucursa_5a9f95_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksucursal',
            index=models.Index(fields=['variante'], name='catalogo_st_variant_8be54a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocksucursal',
            unique_together={('sucursal', 'variante')},
        ),
        migrations.AddIndex(
            model_name='varianteatributo',
            index=models.Index(fields=['variante', 'atributo'], name='catalogo_va_variant_1f2e68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='varianteatributo',
            unique_together={('variante', 'atributo')},
        ),
    ]
