# Generated by Django 5.0.14 on 2026-02-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variante',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
