# Generated by Django 5.0.14 on 2026-02-08 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONTADO', 'Contado'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'QR')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuotas', models.PositiveSmallIntegerField(default=1)),
                ('coeficiente', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('pos_proveedor', models.CharField(blank=True, max_length=40)),
                ('pos_terminal_id', models.CharField(blank=True, max_length=40)),
                ('pos_lote', models.CharField(blank=True, max_length=40)),
                ('pos_cupon', models.CharField(blank=True, max_length=40)),
                ('pos_autorizacion', models.CharField(blank=True, max_length=40)),
                ('pos_marca', models.CharField(blank=True, max_length=20)),
                ('pos_ultimos4', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta')),
            ],
            options={
                'indexes': [models.Index(fields=['venta', 'tipo'], name='ventas_vent_venta_i_3691e7_idx')],
            },
        ),
    ]
