# Generated by Django 5.0.14 on 2026-02-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_ventapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventapago',
            name='recargo_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ventapago',
            name='recargo_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
