# Generated by Django 5.0.14 on 2026-02-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_ventapago_recargo_monto_ventapago_recargo_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('PAYWAY', 'Payway'), ('GETNET', 'Getnet'), ('FISERV', 'Fiserv'), ('MP', 'Mercado Pago'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('banco', models.CharField(max_length=60)),
                ('tarjeta', models.CharField(max_length=30)),
                ('cuotas', models.PositiveSmallIntegerField()),
                ('recargo_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['activo', 'proveedor', 'banco', 'tarjeta', 'cuotas'], name='ventas_plan_activo_ff7725_idx')],
                'unique_together': {('proveedor', 'banco', 'tarjeta', 'cuotas')},
            },
        ),
    ]
