# Generated by Django 5.0.14 on 2026-02-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_plancuotas'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='plancuotas',
            name='ventas_plan_activo_ff7725_idx',
        ),
        migrations.AlterUniqueTogether(
            name='plancuotas',
            unique_together={('tarjeta', 'cuotas')},
        ),
        migrations.AddIndex(
            model_name='plancuotas',
            index=models.Index(fields=['activo', 'tarjeta', 'cuotas'], name='ventas_plan_activo_af8b3e_idx'),
        ),
        migrations.RemoveField(
            model_name='plancuotas',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='plancuotas',
            name='proveedor',
        ),
    ]
