# Generated by Django 5.0.14 on 2026-02-09 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_remove_plancuotas_ventas_plan_activo_ff7725_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventapago',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.plancuotas'),
        ),
    ]
