# Generated by Django 5.0.14 on 2026-02-16 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_corrientes', '0001_initial'),
        ('ventas', '0006_ventapago_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='cuentas_corrientes.cliente'),
        ),
    ]
