# Generated by Django 5.0.14 on 2026-02-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_venta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventapago',
            name='tipo',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'QR'), ('CUENTA_CORRIENTE', 'Cuenta corriente')], max_length=20),
        ),
    ]
