# Generated by Django 5.0.14 on 2026-02-25 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('ventas', '0008_alter_ventapago_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='caja_sesion',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='ventas',
                to='caja.cajasesion',
                db_constraint=False,
                db_index=False,
            ),
        ),
        migrations.AddField(
            model_name='venta',
            name='cajero',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='ventas_realizadas',
                to=settings.AUTH_USER_MODEL,
                db_constraint=False,
                db_index=False,
            ),
        ),
    ]
