# Generated by Django 5.0.14 on 2026-02-25 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('core', '0002_appsetting'),
        ('cuentas_corrientes', '0001_initial'),
        ('ventas', '0009_venta_caja_sesion_venta_cajero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_sucursal',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['sucursal', 'numero_sucursal'], name='ventas_vent_sucursa_df0a8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(fields=('sucursal', 'numero_sucursal'), name='ventas_numero_sucursal_uniq'),
        ),
    ]
