# Generated by Django 5.0.14 on 2026-02-26 21:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_venta_numero_sucursal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='empresa_condicion_fiscal_snapshot',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='venta',
            name='empresa_cuit_snapshot',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='empresa_direccion_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='empresa_nombre_snapshot',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='venta',
            name='empresa_razon_social_snapshot',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='venta',
            name='fiscal_items_iva_contenido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='fiscal_items_otros_impuestos_nacionales_indirectos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='fiscal_items_sin_impuestos_nacionales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='iva_alicuota_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='precio_unitario_iva_contenido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='precio_unitario_sin_impuestos_nacionales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='subtotal_iva_contenido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='subtotal_otros_impuestos_nacionales_indirectos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='subtotal_sin_impuestos_nacionales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
