# Generated by Django 5.0.14 on 2026-03-02 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_venta_empresa_condicion_fiscal_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'permissions': [('usar_caja_pos', 'Puede usar Caja POS')]},
        ),
    ]
