# Generated by Django 5.0.14 on 2026-02-16 14:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0006_ventapago_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['dni'], name='cuentas_cor_dni_2fce31_idx'), models.Index(fields=['apellido', 'nombre'], name='cuentas_cor_apellid_74a2f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='CuentaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_corriente', to='cuentas_corrientes.cliente')),
            ],
            options={
                'verbose_name': 'Cuenta corriente',
                'verbose_name_plural': 'Cuentas corrientes',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCuentaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEBITO', 'Débito (Venta)'), ('CREDITO', 'Crédito (Pago)')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='cuentas_corrientes.cuentacorriente')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_cc', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Movimiento de cuenta corriente',
                'verbose_name_plural': 'Movimientos de cuenta corriente',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='cuentacorriente',
            index=models.Index(fields=['activa'], name='cuentas_cor_activa_883e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocuentacorriente',
            index=models.Index(fields=['cuenta', 'tipo', 'fecha'], name='cuentas_cor_cuenta__afd096_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocuentacorriente',
            index=models.Index(fields=['venta'], name='cuentas_cor_venta_i_9fdfa9_idx'),
        ),
    ]
