# Generated by Django 5.0.14 on 2026-02-25 14:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_appsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abierta_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('cajero_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_abiertas', to=settings.AUTH_USER_MODEL)),
                ('cajero_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_cerradas', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_sesiones', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Sesión de caja',
                'verbose_name_plural': 'Sesiones de caja',
                'ordering': ['-abierta_en'],
                'indexes': [models.Index(fields=['sucursal', 'abierta_en'], name='caja_cajase_sucursa_183abb_idx'), models.Index(fields=['cajero_apertura', 'abierta_en'], name='caja_cajase_cajero__b42289_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cajasesion',
            constraint=models.UniqueConstraint(condition=models.Q(('cerrada_en__isnull', True)), fields=('sucursal',), name='caja_unica_abierta_por_sucursal'),
        ),
    ]
